title: GitHub Learning
author: PrithviWarrier
email: theillusioncreator@gmail.com
theme: minima
description: > # this means to ignore newlines until "baseurl:"
  Sample description
# social links
twitter_username: Notwitter
github_username:  warrierprithvi

show_excerpts: true # set to false to remove excerpts on the homepage
